# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  email_provider_username: <%= ENV["GMAIL_USERNAME"] %>
  email_provider_password: <%= ENV["GMAIL_PASSWORD"] %>
  domain_name: example.com
  secret_key_base: cdb3d48e361db8e65da2fbe3cb561afad9ae8d4ae6e00ae52a8659c1f93bccba19e873f20acbdad7f2d76255b62b7789f18d4d9a496dcc8172b268c6b6d68cc4

test:
  domain_name: example.com 
  secret_key_base: 65b3764051762151eb490bed2219b6cf6458674a38c6fbee3397c39ad9c069324a534888b854fdd0c9e1d54b2cd8b9d2b1bfad323092e872abecd9eea46ca95c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: Admin 
  admin_email: moussasarr490@gmail.com
  admin_password: changeme
  email_provider_username: moussasarr490 
  email_provider_password: f*@S2!M+
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
